### ISSUE TITLE
Some birthdays not exported

### ISSUE THREAD

**Issue by DeXeDeXeD** [deepakmahakale/facebook_birthday_export#2]
Hi.
I used the website and the Chrome extension, unfortunately I miss some birthdays in the CSV. Looks like it's random. I tried 4 times and everytime it imports only 128 events, with the same birtdays missing.
Please tell me how I can help with more details.
Chrome 76.0.3809.132

EDIT: I tried again without scrolling to the end of the page. It imports 25 birthdays and I'm still missing the same birthdays I was missing before. I'd say it's not an issue of "too-much-entries", it's that the script can't see some entries, or maybe the HTML source shows them in another place.

**Comment by deepakmahakale** [comment]
Hi @DeXeDeXeD 
Thanks for reporting the issue

The birthdays missing would be the birthdays from the current week (Todays birthday, tomorrows birthday, etc). They are in a different div structure and I am already working on it.

**Comment by deepakmahakale** [comment]
Created #4 to track the bug for birthdays of the current week.
Closing this issue as the main issue of alternate birthday skip is resolved
