### ISSUE TITLE
Facebook Scrambling Div Names

### ISSUE THREAD

**Issue by sambradbury** [deepakmahakale/facebook_birthday_export#6]
It appears Facebook has started obfuscating the tags in their code to make it more difficult to run scripts like this. The chrome plugin also appears to have stopped function but my description of the issue will refer primarily to the use of the python script. 

The attached screenshot shows the code that appears when"Today's Birthdays" is right clicked and inspect is selected. 

<img width="544" alt="Screen Shot 2020-09-22 at 5 00 36 PM" src="https://user-images.githubusercontent.com/31943456/93942013-2ec3ea80-fcf5-11ea-9a16-d23d2cccbb30.png">

birthday_parser.py runs perfectly fine but it exports an empty CSV file no matter which portion of code is imported into facebook_html.txt 

I have been unable to find any meaningful references to Birthday for any div classes. The only search result that shows us is for the href link to the /events/birthdays page itself. 

My fervor to delete Facebook has only increased since I have realized how difficult they want to make it to download something as simple as birthday's.

**Comment by deepakmahakale** [comment]
Thanks for the report. I noticed this when I was trying to export birthdays myself.

Will find if we can patch something up. 
Maybe getting the outer wrapper should do.

**Comment by sambradbury** [comment]
https://github.com/zagushka/birthday-calendar-extractor This extension seems to work around the issue.
